language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "kats-new-year-app-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: kats-new-year-app
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: 1mkRJ2i+pskAi6RrP+Ow5jpJLe7/21ml1DrrXehTZHrJaVKx6pkO/48T2MAV0bG7zdgKR01yOjX2ddq+xQHVWT2MhP/LmnETB2/nyaK5yGsWOoWfngx+v5NfDChfKjsYG/qYCT8XET1vD7yUjfAlxDO4rIqrn9hqj1zrPL7tSTaYvqj9QO/UsIugxGLoNFWaeewAO/hJzFaTCGelskybX/nraEVEi7f56nIK0hqChQ9C9SWzx3kk1W10DW3r5LlbYVMbHcFk2fnR5vfuDmDlh0VJ5VSxfp98e7/TDFaqhCHMGj1UEaVR8sss241399/0ztLhzfYOgnAMV0/99Sg+/vkQseOoP3uBX1rhftsAJxz5+LfEbj0ncFCRB2th4g/mIhafmAj3u+rwj/t2gKQ67xINFK35ohkV4v+CR69T+QMEGNc52Kp5CsL77EBDZsni+rBzVXUSl54HFLKhNaKdrn1FtCEm7u3UKOXjP3MqoNxCBoEAeESDZLJp33L19+OxKbq9vpIlCzu4LbVx2nyO3lG/MeFjtGiO0jGGBonluLfwFMJ8PgGh5BP1FfrP5ngio80idcXKIBFOb3be5j+sZuiB1vZyddsdFfjxtUQcNS9KrFSdGvR4Qn/d7SIP9Y19PBdZGpw8JB1sVtaHWdaLrXG3Nm36vXy9he6d8N2IjP0=
